---
apiVersion: v1
kind: Namespace
metadata:
  name: Dev


---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: deploy-demo
  name: deploy 
  namespace: Dev  
spec:
  minReadySeconds: 5
  replicas: 6
  selector:
    matchLabels:
      name: deploy-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels: deploy-demo 
    spec:
      containers:
        - image: suri1002/spc:latest
          name: spc
          ports:
            - containerPort: 8080
              protocol: TCP         